# Generated by Django 5.2.5 on 2025-08-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_quiz.student'),
        ),
    ]
